#ifndef _HELLOWORLD_H_
#define _HELLOWORLD_H_

/* Some cross-platform definitions generated by autotools */
#if HAVE_CONFIG_H
#  include <config.h>
#endif /* HAVE_CONFIG_H */

/*
 * Example function
 */
extern void LibHelloWorld(void);

#endif
